server:
  port: 8082

spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://localhost:9411  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

  instance:
    ##EurekaClient 向注册中心发送心跳的时间间隔，（单位：秒）客户端告诉注册服务端自己会按照该规则发送心跳
    lease-renewal-interval-in-seconds: 1
    ##EurekaServer在收到最后一次心跳后等待的时间上限，（单位：秒），超过则剔除。客户端告诉注册服务端自己会按照该规则发送心跳
    lease-expiration-duration-in-seconds: 2
