server:
  port: 8082

spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

  instance:
    ##EurekaClient 向注册中心发送心跳的时间间隔，（单位：秒）客户端告诉注册服务端自己会按照该规则发送心跳
    lease-renewal-interval-in-seconds: 1
    ##EurekaServer在收到最后一次心跳后等待的时间上限，（单位：秒），超过则剔除。客户端告诉注册服务端自己会按照该规则发送心跳
    lease-expiration-duration-in-seconds: 2
mybatis:
  config-locations: classpath:mapping/confg.xml
  mapper-locations: classpath:mapping/mapper/*.xml
  type-aliases-package: com.jk.model
