eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true  #配置可以存在多个生产者实例
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
feign:
  hystrix:
    enabled: true  #配置文件中配置打开断路器
elasticsearch:
  clusterName: my-application
  firstPort: 9300
  ip: 127.0.0.1
  secondPort: 9301
  thirdPort: 9302
    
